language: node_js
node_js:
  - "node"
script:
  - npm run build
before_deploy:
after_success:
  - cp keybase.txt public/keybase.txt
  - npm i -g firebase-tools
  - firebase deploy --token ${FIREBASE_TOKEN}
