language: node_js
install:
  - npm ci
cache:
  directories:
  - "$HOME/.npm"
node_js:
  - "node"
script:
  - npm run build
before_deploy:
after_success:
  - npm i -g firebase-tools
  - firebase deploy --token ${FIREBASE_TOKEN}
